export default {
    QUERY_WEEKLY_LIST: 'QUERY_WEEKLY_LIST',
    QUERY_WEEKLY_DETAIL: 'QUERY_WEEKLY_DETAIL',
    SET_WEEKLY_TITLE: 'SET_WEEKLY_TITLE',
    SET_COLUMN_EDIT_INDEX: 'SET_COLUMN_EDIT_INDEX'
};
